/**
 * reply-language — the Stop hook that catches an English reply to a Korean
 * prompt. Pins the detector's measured thresholds, the transcript walk, the
 * hook's silent paths (a loop here would hang a session), and the installer's
 * hook bookkeeping next to the lint hook.
 */

import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { childEnv } from './helpers/child-env.js';

const SANDBOX = mkdtempSync(join(tmpdir(), 'sprag-reply-lang-'));
const HOME = join(SANDBOX, 'home');
const CFG = join(SANDBOX, 'cfg');
mkdirSync(HOME, { recursive: true });
process.env.HOME = HOME;
process.env.USERPROFILE = HOME;
process.env.XDG_CONFIG_HOME = CFG;
after(() => rmSync(SANDBOX, { recursive: true, force: true }));

const CLI = fileURLToPath(new URL('../bin/cli.js', import.meta.url));
const rl = createRequire(import.meta.url)('../src/reply-language.cjs');
const installer = await import('../src/installer.js');

const KO_PROMPT = '이 함수가 하는 일을 설명해 주세요';
const EN_REPLY = 'This function reads the transcript file, walks the entries in order and returns the last turn so that the caller can compare the language of the prompt with the language of the reply.';
const KO_REPLY = '이 함수는 `readTailLines(path)` 를 호출해 /Users/me/project/src/reply-language.cjs 의 마지막 부분만 읽고, parseEntry 와 isSidechain 같은 식별자를 건너뛴 뒤 마지막 턴을 돌려줍니다.';

const user = (content, extra = {}) => JSON.stringify({ type: 'user', message: { role: 'user', content }, ...extra });
const asst = (text) => JSON.stringify({ type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text }] } });
const toolResult = () => user([{ type: 'tool_result', tool_use_id: 't1', content: 'ok' }]);

test('Korean prompt with an English reply is flagged', () => {
  assert.ok(rl.isKoreanPrompt(KO_PROMPT));
  assert.ok(rl.isEnglishReply(EN_REPLY));
});

test('Korean reply full of code, paths and identifiers is not flagged', () => {
  assert.equal(rl.isEnglishReply(KO_REPLY), false);
  const heavy = KO_REPLY + '\n```js\nconst something = veryLongIdentifier(anotherArgument, yetAnotherArgument, andOneMore);\n```';
  assert.equal(rl.isEnglishReply(heavy), false);
});

test('English prompt is not a Korean prompt', () => {
  assert.equal(rl.isKoreanPrompt('Explain what this function does'), false);
});

test('a reply under 80 Latin letters is not flagged', () => {
  assert.equal(rl.isEnglishReply('Done. All tests pass.'), false);
});

test('cleanText drops reminders, code, URLs and paths', () => {
  const out = rl.cleanText('a <system-reminder>secret</system-reminder> `x` https://e.com/a /usr/bin/node ~/x/y ```z\nq``` b');
  assert.equal(out.replace(/\s+/g, ' ').trim(), 'a b');
});

test('a prompt asking for English is skipped', () => {
  const file = join(SANDBOX, 'asks-english.jsonl');
  writeFileSync(file, [user('이 내용을 영어로 번역해 주세요'), asst(EN_REPLY)].join('\n'));
  assert.equal(rl.checkReplyLanguage(file), null);
});

test('checkReplyLanguage reports ratios for the bad case and never throws', () => {
  const file = join(SANDBOX, 'bad.jsonl');
  writeFileSync(file, [user(KO_PROMPT), asst(EN_REPLY)].join('\n'));
  const found = rl.checkReplyLanguage(file);
  assert.ok(found.userHangulRatio >= 0.3);
  assert.ok(found.replyHangulRatio < 0.15);
  assert.ok(found.replyLatin >= 80);
  assert.equal(rl.checkReplyLanguage(join(SANDBOX, 'missing.jsonl')), null);
  assert.equal(rl.checkReplyLanguage(undefined), null);
});

test('lastTurn: a tool_result resets the reply to the final text', () => {
  const turn = rl.lastTurn([user(KO_PROMPT), asst('Let me look at the file first, one moment please.'), toolResult(), asst('최종 답변입니다')]);
  assert.equal(turn.reply, '최종 답변입니다');
  assert.equal(turn.prompt, KO_PROMPT);
});

test('lastTurn: command, notification and hand-back entries are not prompts', () => {
  const lines = [
    user(KO_PROMPT),
    asst('답변'),
    user('<command-name>/clear</command-name>'),
    user('<local-command-stdout>x</local-command-stdout>'),
    user('<task-notification>done</task-notification>'),
    user('Caveat: generated by tooling'),
    user('[Subagent hand-back] report'),
    user('<agent-message>hi</agent-message>'),
    user('meta text', { isMeta: true }),
  ];
  const turn = rl.lastTurn(lines);
  assert.equal(turn.prompt, KO_PROMPT);
  assert.equal(turn.reply, '답변');
});

test('lastTurn: sidechain entries and unparsable lines are ignored', () => {
  const side = JSON.stringify({ type: 'assistant', isSidechain: true, message: { content: [{ type: 'text', text: 'sidechain English words' }] } });
  const turn = rl.lastTurn(['not json', user(KO_PROMPT), side, asst('본문')]);
  assert.equal(turn.reply, '본문');
});

function cli(payload, argv = ['korean', '--reply-hook']) {
  return spawnSync(process.execPath, [CLI, ...argv], {
    env: childEnv({ HOME, USERPROFILE: HOME, XDG_CONFIG_HOME: CFG }),
    input: payload === undefined ? '' : JSON.stringify(payload),
    encoding: 'utf8',
  });
}

function writeConfig(cfg) {
  const dir = join(CFG, 'claude-token-saver');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'config.json'), JSON.stringify(cfg));
}

test('hook CLI: blocks the bad case, stays silent otherwise', () => {
  const bad = join(SANDBOX, 'cli-bad.jsonl');
  writeFileSync(bad, [user(KO_PROMPT), asst(EN_REPLY)].join('\n'));
  const good = join(SANDBOX, 'cli-good.jsonl');
  writeFileSync(good, [user(KO_PROMPT), asst(KO_REPLY)].join('\n'));

  writeConfig({ koreanStyle: { enabled: true } });
  let out = cli({ transcript_path: bad });
  assert.equal(out.status, 0, out.stderr);
  const parsed = JSON.parse(out.stdout);
  assert.equal(parsed.decision, 'block');
  assert.match(parsed.reason, /한국어로 다시 답하십시오/);

  out = cli({ transcript_path: bad, stop_hook_active: true });
  assert.equal(out.status, 0);
  assert.equal(out.stdout, '');

  out = cli({ transcript_path: good });
  assert.equal(out.status, 0);
  assert.equal(out.stdout, '');

  out = cli(undefined);
  assert.equal(out.status, 0);
  assert.equal(out.stdout, '');

  writeConfig({ koreanStyle: { enabled: true }, koreanReplyCheck: false });
  out = cli({ transcript_path: bad });
  assert.equal(out.status, 0);
  assert.equal(out.stdout, '');

  writeConfig({ koreanReplyCheck: true });
  out = cli({ transcript_path: bad });
  assert.equal(out.stdout, '', 'korean style disabled means no-op');
});

test('korean reply on|off writes the config key', () => {
  writeConfig({ koreanStyle: { enabled: true } });
  let out = cli(undefined, ['korean', 'reply', 'off']);
  assert.equal(out.status, 0, out.stderr);
  const cfgFile = join(CFG, 'claude-token-saver', 'config.json');
  assert.equal(JSON.parse(readFileSync(cfgFile, 'utf8')).koreanReplyCheck, false);
  out = cli(undefined, ['korean', 'reply', 'on']);
  assert.equal(JSON.parse(readFileSync(cfgFile, 'utf8')).koreanReplyCheck, true);
  out = cli(undefined, ['korean', 'reply', 'bogus']);
  assert.equal(out.status, 1);
});

function stopEntries() {
  const s = JSON.parse(readFileSync(join(HOME, '.claude', 'settings.json'), 'utf8'));
  return s.hooks?.Stop ?? [];
}

test('installer: install is idempotent and remove touches only its own hook', () => {
  rmSync(join(HOME, '.claude'), { recursive: true, force: true });
  assert.equal(installer.installReplyLanguageHook().action, 'created');
  assert.equal(installer.installReplyLanguageHook().action, 'exists');
  assert.equal(stopEntries().length, 1);
  assert.equal(installer.installKoreanLintHook().action, 'created');

  // Removing the lint hook leaves the reply hook.
  assert.equal(installer.removeKoreanLintHook().action, 'removed');
  assert.equal(stopEntries().length, 1);
  assert.equal(installer.installKoreanLintHook().action, 'created');

  // Removing the reply hook leaves the lint hook.
  assert.equal(installer.removeReplyLanguageHook().action, 'removed');
  assert.equal(stopEntries().length, 0);
  const s = JSON.parse(readFileSync(join(HOME, '.claude', 'settings.json'), 'utf8'));
  assert.equal(s.hooks.PostToolUse.length, 1);
  assert.equal(installer.removeReplyLanguageHook().action, 'absent');
});

test('installer: a Stop hook from someone else is kept and a non-array Stop is refused', () => {
  const file = join(HOME, '.claude', 'settings.json');
  writeFileSync(file, JSON.stringify({ hooks: { Stop: [{ hooks: [{ type: 'command', command: 'echo mine' }] }] } }));
  assert.equal(installer.installReplyLanguageHook().action, 'created');
  assert.equal(stopEntries().length, 2);
  assert.equal(installer.removeReplyLanguageHook().action, 'removed');
  assert.equal(stopEntries().length, 1);
  writeFileSync(file, JSON.stringify({ hooks: { Stop: 'nope' } }));
  assert.equal(installer.installReplyLanguageHook().action, 'skipped');
});
