/**
 * Handoff template — captures enough state at session-cap time that a fresh
 * Claude Code session can pick up the work without a long prelude.
 *
 * Output: `./HANDOFF-YYYY-MM-DD-HHMM.md` in the caller's cwd. We never
 * overwrite — if the path is taken we add a `-N` suffix.
 *
 * What goes in:
 *   - Header: timestamp, cwd, git branch / HEAD / dirty file list
 *   - Cap snapshot: 5h/7d % and resets-in (when known)
 *   - Empty fillable sections the user pastes context into
 *   - A one-line resume prompt for the next session
 */

import { writeFileSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join, resolve } from 'node:path';

function pad(n) {
  return String(n).padStart(2, '0');
}

function ymd(d = new Date()) {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

function hhmm(d = new Date()) {
  return `${pad(d.getHours())}${pad(d.getMinutes())}`;
}

function safeGit(cmd, cwd) {
  try {
    return execSync(`git ${cmd}`, {
      cwd,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return '';
  }
}

function gitSnapshot(cwd) {
  // `rev-parse --git-dir` succeeds in any repo, including a freshly-init'd one
  // with no commits yet (where `rev-parse HEAD` would fail). We use it as the
  // "is this a repo?" probe.
  const gitDir = safeGit('rev-parse --git-dir', cwd);
  if (!gitDir) return null;
  const branch = safeGit('rev-parse --abbrev-ref HEAD', cwd) || '(no commits)';
  const head = safeGit('rev-parse --short HEAD', cwd);
  const status = safeGit('status --short', cwd);
  return { branch, head, status };
}

function formatResetIn(resetsAt, now = new Date()) {
  if (!Number.isFinite(resetsAt)) return null;
  const remaining = Math.max(0, resetsAt - Math.floor(now.getTime() / 1000));
  if (remaining <= 0) return '0m';
  const h = Math.floor(remaining / 3600);
  const m = Math.floor((remaining % 3600) / 60);
  if (h > 0) return `${h}h ${m}m`;
  return `${m}m`;
}

function pickPath(cwd, now) {
  const stem = `HANDOFF-${ymd(now)}-${hhmm(now)}`;
  const direct = join(cwd, `${stem}.md`);
  if (!existsSync(direct)) return direct;
  for (let i = 2; i < 100; i++) {
    const candidate = join(cwd, `${stem}-${i}.md`);
    if (!existsSync(candidate)) return candidate;
  }
  return join(cwd, `${stem}-${Date.now()}.md`);
}

function renderTemplate({ now, cwd, git, caps }) {
  const lines = [];
  lines.push(`# Handoff — ${ymd(now)} ${pad(now.getHours())}:${pad(now.getMinutes())}`);
  lines.push('');
  lines.push(`Generated by \`claude-token-saver handoff\`.`);
  lines.push('');
  lines.push('## Context');
  lines.push('');
  lines.push(`- cwd: \`${cwd}\``);
  if (git) {
    lines.push(`- git branch: \`${git.branch}\`${git.head ? ` @ \`${git.head}\`` : ''}`);
    if (git.status) {
      lines.push('- dirty files:');
      lines.push('  ```');
      for (const line of git.status.split('\n')) lines.push(`  ${line}`);
      lines.push('  ```');
    } else {
      lines.push('- working tree: clean');
    }
  } else {
    lines.push('- git: (not a repo)');
  }
  lines.push('');

  lines.push('## Cap snapshot');
  lines.push('');
  if (caps) {
    const fmtRow = (label, info) => {
      if (!info) return `- ${label}: (unknown — stdin had no rate-limit info)`;
      const reset = formatResetIn(info.resetsAt, now);
      const tail = reset ? `, resets in ${reset}` : '';
      return `- ${label}: ${Math.round(info.usedPct)}%${tail}`;
    };
    lines.push(fmtRow('5-hour window', caps.fiveHour));
    lines.push(fmtRow('7-day window', caps.sevenDay));
  } else {
    lines.push('- (no cap data — run `handoff` from a Claude Code session for live numbers)');
  }
  lines.push('');

  lines.push('## What I just did');
  lines.push('');
  lines.push('- _(fill in: 1–3 bullets describing the most recent work)_');
  lines.push('');

  lines.push('## What\'s left (TODO)');
  lines.push('');
  lines.push('- [ ] _(fill in)_');
  lines.push('');

  lines.push('## Where to pick up next');
  lines.push('');
  lines.push('- _(file paths, function names, the exact next step)_');
  lines.push('');

  lines.push('## Watch out for');
  lines.push('');
  lines.push('- _(non-obvious gotchas, half-finished refactors, failing tests)_');
  lines.push('');

  lines.push('## Resume prompt for the next Claude Code session');
  lines.push('');
  lines.push('```');
  lines.push('Read the most recent HANDOFF-*.md in this directory and continue the work.');
  lines.push('```');
  lines.push('');

  return lines.join('\n') + '\n';
}

/**
 * Write a handoff file in the given cwd.
 *
 * @param {object} [opts]
 * @param {string} [opts.cwd=process.cwd()]
 * @param {object|null} [opts.caps] - { fiveHour, sevenDay } from extractCaps
 * @param {Date} [opts.now=new Date()]
 * @returns {{ path: string, git: { branch: string, head: string, status: string } | null }}
 */
export function writeHandoff({ cwd = process.cwd(), caps = null, now = new Date() } = {}) {
  const absCwd = resolve(cwd);
  const git = gitSnapshot(absCwd);
  const path = pickPath(absCwd, now);
  const body = renderTemplate({ now, cwd: absCwd, git, caps });
  writeFileSync(path, body);
  return { path, git };
}
